version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd windlot && npm install
  build:
    commands:
      - npm run-script build
      - cp ../appspec.yml ./build/appspec.yml
      - cp -r ../scripts ./build/scripts/
      - cp package.json ./build/package.json

artifacts:
  base-directory: ./windlot/build
  files:
    - '**/*'

cache:
  paths:
    - './windlot/node_modules/**/*'