version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd windlot && npm install
  build:
    commands:
      - npm run-script build

artifacts:
  base-directory: ./windlot/build
  files:
    - '**/*'

cache:
  paths:
    - './windlot/node_modules/**/*'