/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:6ccd2920-9a3b-4802-8047-85e43e4294cc",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Gsk51O8df",
    "aws_user_pools_web_client_id": "359kocdsoomuu0t6r7mtl8folb",
    "oauth": {}
};


export default awsmobile;
